POST  http://localhost:5000/register
Content-Type: application/json

{
    "username" : "raju",
    "password" : "raju@123",
    "role" : "user"
}
###


POST  http://localhost:5000/login
Content-Type: application/json

{
    "username" : "saikiran",
    "password" : "saikiran@123"
}
###

POST http://localhost:5000/addtask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWtpcmFuIiwiaWF0IjoxNzE0NTUyNDA4fQ.R3m4RUiZOo1J2EHGT-2JcYh5R0LM97hE3hzLvcjRB9Y
Content-Type: application/json

{
    "title" : "News",
    "description" : "Get the latest news and breaking news updates on Business, Politics,",
    "status" : true,
    "assigneeId" : 6,
    "createdAt" : "2024-04-13",
    "updatedAt" : "2024-05-01"
}
###

GET  http://localhost:5000/getData?user_id=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWtpcmFuIiwiaWF0IjoxNzE0NTUyNDA4fQ.R3m4RUiZOo1J2EHGT-2JcYh5R0LM97hE3hzLvcjRB9Y
Content-Type: application/json
###

GET  http://localhost:5000/getAllData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWtpcmFuIiwiaWF0IjoxNzE0NTUyNDA4fQ.R3m4RUiZOo1J2EHGT-2JcYh5R0LM97hE3hzLvcjRB9Y
Content-Type: application/json
###

PUT  http://localhost:5000/updateData
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWtpcmFuIiwiaWF0IjoxNzE0NTUyNDA4fQ.R3m4RUiZOo1J2EHGT-2JcYh5R0LM97hE3hzLvcjRB9Y
Content-Type: application/json

{
    "title" : "entertainment",
    "description" : "i have go out at 6pm today",
    "status" : true,
    "assigneeId" : 6,
    "createdAt" : "2024-04-13",
    "updatedAt" : "2024-06-01",
    "taskId" : 5
}
###

DELETE  http://localhost:5000/deleteTask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaWtpcmFuIiwiaWF0IjoxNzE0NTUyNDA4fQ.R3m4RUiZOo1J2EHGT-2JcYh5R0LM97hE3hzLvcjRB9Y
Content-Type: application/json

{
    "taskId" : 5
}